version: '3'
services:
  vue:
    build:
      context: .
    volumes:
      - ./origin-prac-app:/app
    ports:
      - '5173:5173'
    # 1 vueを起動するコマンド
    command: npm run dev -- --host

# @          @@          @@          @@          @@          @@          @@          @@          @
# 1
# -- --host
# command: npm run dev -- --host は、Docker コンテナ内で Vite の開発サーバーを起動するときに、外部(local)から
# のアクセスを許可するための設定。
# これを付けないと、portsの設定のみではlocalのブラウザで表示できない
# npm run dev(＝vite)コマンドに --host オプションを追加して、外部からアクセスできるように設定する必要がある。
# ------------------------------------------------------------------------------------------------
# 通常、Vite などの開発サーバーは「ローカルホスト」（自分のコンピュータ内の特定のネットワーク）上で動作する。つまり、
# 自分のコンピュータからしかその開発サーバーにアクセスできない状態になっている。
# しかし、Docker コンテナの中で開発サーバーを立てた場合、コンテナはホストマシン（自分のPC）とは異なる仮想環境で動いてい
# るため、ホストマシンからコンテナ内の開発サーバーにアクセスするためには設定が必要になる。
